# Molecule managed

---
all:
  hosts:
    fedora: &id001
      ansible_connection: docker
    ubuntu: &id002
      ansible_connection: docker
ungrouped:
  hosts:
    fedora: *id001
    ubuntu: *id002
  vars: {}
