---
- name: Update pacman cache (Arch Linux)
  become: true
  community.general.pacman:
    update_cache: true
  changed_when: false

- name: Install vim (Arch Linux)
  become: true
  community.general.pacman:
    name:
      - git
      - vim
      - vim-syntastic
    state: present
