---
- name: Update Repository cache when Ubuntu
  become: true
  apt:
    update_cache: true
    cache_valid_time: 3600
    force_apt_get: true
  when: ansible_facts['os_family'] == 'Debian' or ansible_facts['os_family'] == 'Ubuntu'

- name: Install vim
  become: true
  package:
    name:
      - git
      - vim
      - vim-syntastic
    state: present
  tags:
    - vim

- name: create ~/.config/vim diretory
  become: false
  file:
    path: "~/.config/vim/"
    state: directory
    mode: 0755
  tags:
    - vim

- name: Clone vundle from github
  become: false
  git:
    repo: https://github.com/VundleVim/Vundle.vim.git
    dest: "~/.config/vim/bundle/Vundle.vim"
    version: master
    update: false
  tags:
    - vim

- name: Generate ~/.vimrc
  become: false
  template:
    src: vimrc.j2
    dest: "~/.vimrc"
    mode: "0644"
  notify: install plugins
  tags:
    - vim

- name: Check existence of spell-check file
  stat:
    path: "~/.config/vim/en.utf-8.add"
  register: spell_check_file
  tags:
    - vim

- name: Touch spell-check file
  become: false
  file:
    path: "~/.config/vim/en.utf-8.add"
    state: touch
    mode: 0644
  when: not spell_check_file.stat.exists
  tags:
    - vim

- name: vim info
  become: false
  debug:
    msg: "See ':h vundle' for more details."
  tags:
    - vim
