---
- name: Install vim
  ansible.builtin.include_tasks: install.yml
  when: install | default(true) | bool

- name: Uninstall vim
  ansible.builtin.include_tasks: uninstall.yml
  when: not (install | default(true) | bool)
