---
- name: Install vim
  package:
    name:
      - git
      - vim
    state: present
    retries: 2
  tags:
    - vim

- name: create ~/.vim diretory
  become: false
  file:
    path: "~/.vim/"
    state: directory
    mode: 0755
  tags:
    - vim

- name: Clone vundle from github
  become: false
  git:
    repo: https://github.com/VundleVim/Vundle.vim.git
    dest: "~/.vim/bundle/Vundle.vim"
    version: master
    update: no
  tags:
    - vim

- name: Generate ~/.vimrc
  become: false
  template:
    src: vimrc.j2
    dest: "~/.vimrc"
    mode: "0644"
  notify: install plugins
  tags:
    - vim

- name: Check existance of spell-check file
  stat:
    path: "~/.vim/en.utf-8.add"
  register: spell_check_file
  tags:
    - vim

- name: Touch spell-check file
  become: false
  file:
    path: "~/.vim/en.utf-8.add"
    state: touch
    mode: 0644
  when: not spell_check_file.stat.exists
  tags:
    - vim

- name: vim info
  debug:
    msg: "See ':h vundle' for more details."
  tags:
    - vim
