---
- name: Uninstall vim
  become: true
  ansible.builtin.package:
    name:
      - vim-syntastic
      - vim
    state: absent
  tags:
    - vim

- name: Backup ~/.config/vim to /tmp/vim
  become: false
  ansible.builtin.command:
    cmd: "cp -a {{ ansible_env['HOME'] }}/.config/vim /tmp/vim"
    creates: /tmp/vim
    removes: "{{ ansible_env['HOME'] }}/.config/vim"

- name: Remove ~/.config/vim directory
  become: false
  ansible.builtin.file:
    path: "~/.config/vim/"
    state: absent
  tags:
    - vim

- name: Backup ~/.vimrc to /tmp/vim/.vimrc
  become: false
  ansible.builtin.command:
    cmd: "cp -a {{ ansible_env['HOME'] }}/.vimrc /tmp/vim/.vimrc"
    creates: /tmp/vim/.vimrc
    removes: "{{ ansible_env['HOME'] }}/.vimrc"

- name: Remove ~/.vimrc
  become: false
  ansible.builtin.file:
    path: "~/.vimrc"
    state: absent
  tags:
    - vim
