---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    # image: docker.io/pycontribs/centos:8
    # image: ansible/ansible
    image: geerlingguy/docker-ubuntu2004-ansible
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
