---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: ubuntu
    image: geerlingguy/docker-ubuntu2004-ansible
    pre_build_image: true
  - name: arch
    image: jahrik/docker-archlinux-ansible
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
